export const LOGIN_USER = "LOGIN_USER";
export const SET_CURRENT_ERROR = "SET_CURRENT_ERROR";
export const LOAD_COMPONENT = "LOAD_COMPONENT";
export const GET_USER_DISHES = "GET_USER_DISHES";
export const GET_USER_RECIPES = "GET_USER_RECIPES";